# Generated by Django 4.1.7 on 2023-03-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_article_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desription',
            new_name='description',
        ),
    ]
